language: haskell
ghc: 8.0.2
cache:
  directories:
  - $HOME/.stack/
  - $HOME/.local/bin/
  - .stack-work/
branches:
  only:
  - master
  - develop
  - /^feature\/\w+/
before_install:
- mkdir -p ~/.local/bin
- export PATH=~/.local/bin:$PATH
- if [[ ! -x ~/.local/bin/stack ]]; \
then travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | \
tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; \
chmod a+x ~/.local/bin/stack; \
fi
- stack --version
- stack setup
- stack exec -- ghc --version
install:
- stack install codecov-haskell
- stack install --only-dependencies
script:
- stack test --coverage
- stack build
after_script:
- stack exec codecov-haskell -- --exclude-dir=test
notifications:
  email: false
