name: bitcoin-hall
version: '0.1.0.0'
category: Bitcoin, Finance
author: Kunio SAWATANI
maintainer: devel@fathens.org
copyright: fathens.org
license: GPL-3
homepage: https://github.com/sawatani/bitcoin-hall#readme
extra-source-files:
- README.md

dependencies:
- base >=4.7 && <5
- binary >=0.8.3.0
- bytestring >=0.10.8.1
- text >=1.2.2.1
- mtl >= 2.2.1

library:
  source-dirs: src

executables:
  bitcoin-hall:
    main: Main.hs
    source-dirs: app
    dependencies:
    - bitcoin-hall

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - bitcoin-hall
    - hspec >=2.4.3
